-- ============================================
-- AJUSTE DE ESTRUTURA - POSTGRESQL
-- ============================================

-- Modalidade
CREATE TABLE IF NOT EXISTS modalidade (
  idmodalidade integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  situacao smallint NOT NULL DEFAULT 1 CHECK (situacao IN (0,1)),
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Turma
CREATE TABLE IF NOT EXISTS turma (
  idturma integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  modalidade_id integer NOT NULL,
  dias_semana varchar NOT NULL,
  horario time NOT NULL,
  professor varchar,
  limite_alunos integer CHECK (limite_alunos IS NULL OR limite_alunos > 0),
  situacao smallint NOT NULL DEFAULT 1 CHECK (situacao IN (0,1)),
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_turma_modalidade
    FOREIGN KEY (modalidade_id) REFERENCES public.modalidade(idmodalidade)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Aluno
CREATE TABLE IF NOT EXISTS aluno (
  idaluno integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  telefone varchar NOT NULL,
  modalidade_id integer NOT NULL,
  data_inicio date,
  dia_vencimento integer NOT NULL CHECK (dia_vencimento BETWEEN 1 AND 31),
  notificacao_whatsapp smallint NOT NULL DEFAULT 1 CHECK (notificacao_whatsapp IN (0,1)),
  situacao smallint NOT NULL DEFAULT 1 CHECK (situacao IN (0,1)),
  observacao text,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valor_mensalidade numeric(10,2) NOT NULL DEFAULT 0 CHECK (valor_mensalidade >= 0),
  plano text NOT NULL DEFAULT 'mensal',
  data_inicio_contrato date,
  data_vencimento_contrato date,
  CONSTRAINT fk_aluno_modalidade
    FOREIGN KEY (modalidade_id) REFERENCES public.modalidade(idmodalidade)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_contrato_datas
    CHECK (
      data_inicio_contrato IS NULL
      OR data_vencimento_contrato IS NULL
      OR data_vencimento_contrato >= data_inicio_contrato
    )
);

-- Relacionamento N:N entre aluno e turma
CREATE TABLE IF NOT EXISTS aluno_turma (
  aluno_id integer NOT NULL,
  turma_id integer NOT NULL,
  PRIMARY KEY (aluno_id, turma_id),
  CONSTRAINT aluno_turma_aluno_id_fkey
    FOREIGN KEY (aluno_id) REFERENCES aluno(idaluno)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT aluno_turma_turma_id_fkey
    FOREIGN KEY (turma_id) REFERENCES turma(idturma)
    ON UPDATE CASCADE ON DELETE CASCADE
);

-- Configuração
CREATE TABLE IF NOT EXISTS configuracao (
  idconfiguracao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_arena varchar,
  telefone_arena varchar,
  valor_mensalidade numeric(10,2) CHECK (valor_mensalidade IS NULL OR valor_mensalidade >= 0),
  dias_lembrete integer CHECK (dias_lembrete IS NULL OR dias_lembrete >= 0),
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Gasto
CREATE TABLE IF NOT EXISTS gasto (
  idgasto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao text NOT NULL,
  valor numeric(10,2) NOT NULL CHECK (valor >= 0),
  categoria text NOT NULL,
  data date NOT NULL,
  observacao text,
  criado_em timestamp DEFAULT now()
);

-- Grupo WhatsApp
CREATE TABLE IF NOT EXISTS grupo_whatsapp (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  link text NOT NULL,
  tipo varchar NOT NULL DEFAULT 'geral',
  referencia_id integer,
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Usuário
CREATE TABLE IF NOT EXISTS public.usuario (
  idusuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  email varchar NOT NULL UNIQUE,
  senha varchar NOT NULL,
  situacao smallint NOT NULL DEFAULT 1 CHECK (situacao IN (0,1)),
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Mensagem
CREATE TABLE IF NOT EXISTS mensagem (
  idmensagem integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar NOT NULL,
  destino varchar,
  mensagem text NOT NULL,
  usuario_id integer,
  enviado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_mensagem_usuario
    FOREIGN KEY (usuario_id) REFERENCES usuario(idusuario)
    ON UPDATE CASCADE ON DELETE SET NULL
);

-- Mensalidade
CREATE TABLE IF NOT EXISTS mensalidade (
  idmensalidade integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aluno_id integer NOT NULL,
  valor numeric(10,2) NOT NULL CHECK (valor >= 0),
  mes_referencia varchar(7) NOT NULL, -- ex: 2026-04
  data_vencimento date NOT NULL,
  data_pagamento date,
  situacao smallint NOT NULL DEFAULT 0 CHECK (situacao IN (0,1,2)),
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_mensalidade_aluno
    FOREIGN KEY (aluno_id) REFERENCES aluno(idaluno)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT uq_mensalidade_aluno_mes UNIQUE (aluno_id, mes_referencia),
  CONSTRAINT chk_pagamento_data
    CHECK (data_pagamento IS NULL OR data_pagamento >= data_vencimento OR data_pagamento <= CURRENT_DATE)
);

-- Notificação
CREATE TABLE IF NOT EXISTS notificacao (
  idnotificacao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aluno_id integer NOT NULL,
  tipo varchar NOT NULL,
  mensagem text NOT NULL,
  enviado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  situacao smallint NOT NULL DEFAULT 1 CHECK (situacao IN (0,1)),
  CONSTRAINT fk_notificacao_aluno
    FOREIGN KEY (aluno_id) references aluno(idaluno)
    ON UPDATE CASCADE ON DELETE CASCADE
);

-- Presença
CREATE TABLE IF NOT EXISTS presenca (
  idpresenca integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aluno_id integer NOT NULL,
  turma_id integer NOT NULL,
  data_treino date NOT NULL,
  situacao smallint NOT NULL DEFAULT 1 CHECK (situacao IN (0,1)),
  criado_em timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_presenca_aluno
    FOREIGN KEY (aluno_id) REFERENCES aluno(idaluno)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_presenca_turma
    FOREIGN KEY (turma_id) REFERENCES turma(idturma)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT uq_presenca UNIQUE (aluno_id, turma_id, data_treino)
);